"""Add student_profile_id to ParentProfile

Revision ID: 3fcdfcc39a92
Revises: 8e3dde415994
Create Date: 2024-09-09 15:58:04.233678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcdfcc39a92'
down_revision: Union[str, None] = '8e3dde415994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_profiles', sa.Column('student_profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'parent_profiles', 'student_profiles', ['student_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_profiles', type_='foreignkey')
    op.drop_column('parent_profiles', 'student_profile_id')
    # ### end Alembic commands ###
