"""revised structure of language table for consistency

Revision ID: 62e5d7b8615b
Revises: fc73bdda233f
Create Date: 2024-09-10 12:51:07.857029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e5d7b8615b'
down_revision: Union[str, None] = 'fc73bdda233f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint('student_profiles_ibfk_6', 'student_profiles', type_='foreignkey')
    op.drop_constraint('student_profiles_ibfk_30', 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'languages', ['primary_language_id'], ['id'])
    op.create_foreign_key(None, 'student_profiles', 'languages', ['other_language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key('student_profiles_ibfk_30', 'student_profiles', 'primary_languages', ['primary_language_id'], ['id'])
    op.create_foreign_key('student_profiles_ibfk_6', 'student_profiles', 'other_languages', ['other_language_id'], ['id'])
    op.drop_table('languages')
    # ### end Alembic commands ###
