"""Add new fields to StudentProfile

Revision ID: a04ec7e958c7
Revises: 69943b794b76
Create Date: 2024-09-09 15:45:04.451765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04ec7e958c7'
down_revision: Union[str, None] = '69943b794b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('preferred_name', sa.String(length=80), nullable=True))
    op.add_column('student_profiles', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('gender_identity', sa.String(length=50), nullable=True))
    op.add_column('student_profiles', sa.Column('home_address', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('phone_numbers', sa.String(length=255), nullable=True))
    op.add_column('student_profiles', sa.Column('email_address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'email_address')
    op.drop_column('student_profiles', 'phone_numbers')
    op.drop_column('student_profiles', 'home_address')
    op.drop_column('student_profiles', 'gender_identity')
    op.drop_column('student_profiles', 'gender')
    op.drop_column('student_profiles', 'preferred_name')
    # ### end Alembic commands ###
