"""Add many demographic fields

Revision ID: aaab82c89c9d
Revises: aa98a48b6258
Create Date: 2024-07-02 18:30:39.802373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aaab82c89c9d'
down_revision: Union[str, None] = 'aa98a48b6258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ethnic_backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('racial_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('relationship', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('parent_guardian', sa.String(length=255), nullable=True),
    sa.Column('demographic_info', sa.Text(), nullable=True),
    sa.Column('discipline_records', sa.Text(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('racial_category_id', sa.Integer(), nullable=True),
    sa.Column('ethnic_background_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=255), nullable=True),
    sa.Column('pronouns', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('family_structure', sa.String(length=50), nullable=True),
    sa.Column('custodial_arrangements', sa.Text(), nullable=True),
    sa.Column('hispanic_latino_origin', sa.Boolean(), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('other_languages', sa.String(length=50), nullable=True),
    sa.Column('english_proficiency', sa.String(length=50), nullable=True),
    sa.Column('esl_ell_status', sa.Boolean(), nullable=True),
    sa.Column('citizenship_status', sa.String(length=50), nullable=True),
    sa.Column('immigration_status', sa.String(length=50), nullable=True),
    sa.Column('date_of_entry_us', sa.Date(), nullable=True),
    sa.Column('free_reduced_lunch_eligibility', sa.Boolean(), nullable=True),
    sa.Column('family_income_bracket', sa.String(length=50), nullable=True),
    sa.Column('parent_education_level', sa.String(length=50), nullable=True),
    sa.Column('parent_occupation', sa.String(length=50), nullable=True),
    sa.Column('current_grade_level', sa.String(length=10), nullable=True),
    sa.Column('previous_schools', sa.Text(), nullable=True),
    sa.Column('date_of_entry_school_system', sa.Date(), nullable=True),
    sa.Column('projected_graduation_year', sa.Date(), nullable=True),
    sa.Column('iep_status', sa.Boolean(), nullable=True),
    sa.Column('plan_504_status', sa.Boolean(), nullable=True),
    sa.Column('gifted_talented_program', sa.Boolean(), nullable=True),
    sa.Column('transportation', sa.String(length=50), nullable=True),
    sa.Column('bus_route_number', sa.String(length=50), nullable=True),
    sa.Column('sports_team_participation', sa.Text(), nullable=True),
    sa.Column('club_memberships', sa.Text(), nullable=True),
    sa.Column('after_school_program', sa.Text(), nullable=True),
    sa.Column('internet_access', sa.Boolean(), nullable=True),
    sa.Column('device_ownership', sa.String(length=50), nullable=True),
    sa.Column('active_duty_military_parent', sa.Boolean(), nullable=True),
    sa.Column('veteran_status_parent', sa.Boolean(), nullable=True),
    sa.Column('homeless_status', sa.Boolean(), nullable=True),
    sa.Column('migrant_education_program', sa.Boolean(), nullable=True),
    sa.Column('foster_care_involvement', sa.Boolean(), nullable=True),
    sa.Column('tribe_membership', sa.Boolean(), nullable=True),
    sa.Column('religious_affiliation', sa.String(length=50), nullable=True),
    sa.Column('church_affiliation', sa.String(length=50), nullable=True),
    sa.Column('school_assigned_id', sa.String(length=50), nullable=True),
    sa.Column('state_assigned_id', sa.String(length=50), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['ethnic_background_id'], ['ethnic_backgrounds.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.ForeignKeyConstraint(['racial_category_id'], ['racial_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_table('student_profiles')
    op.drop_table('siblings')
    op.drop_table('parent_profiles')
    op.drop_table('emergency_contacts')
    op.drop_table('racial_categories')
    op.drop_table('genders')
    op.drop_table('ethnic_backgrounds')
    op.drop_table('countries')
    # ### end Alembic commands ###
